name:               "Ylixir"
description:        "All things ylixir."

url:                "https://ylixir.github.io"
author:             "Jon Allen"
email:              "ylixir@gmail.com"
profile_image: "assets/img/myAvatar.svg"
twitter:            "ylixir"
github:             "ylixir"
linkedin:           "ylixir"
facebook:           "ylixir"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Projects"
    href:           "/projects"
  - name:           "Interests"
    href:           "/interests"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate